#! /usr/bin/sh

# Alternative which should not be used until eww fixes for loops,
# unless you plan on changing the configured keyboard layouts
# on the fly often

# get_keymap_info() {
#     grep -e "$1$" /usr/share/X11/xkb/rules/base.lst | \
#         sed "s/$1//; s/://" | \
#         awk '{printf "{\"layout\": \"%s\", \"variant\": \"%s\"}", toupper($NF), toupper($(3-NF)) }'
# }
#
# report() {
#     main_keyboard=$(hyprctl devices -j | jq '.keyboards | map(select(.main))[0] | {active_keymap, layout, variant}')
#     active=$(get_keymap_info "$(echo $main_keyboard | jq --raw-output '.active_keymap')")
#     configured=$(echo $main_keyboard | \
#         jq --compact-output '[.layout, .variant] | map(ascii_upcase | split(",")) | transpose | map({layout: .[0], variant: .[1]})')
#     echo "{\"active\": $active, \"configured\": $configured}"
# }
#
# report
# socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
#     case $line in
#         activelayout*) report;;
#     esac
# done

report_short_name() {
    echo $(grep -e "$1$" /usr/share/X11/xkb/rules/base.lst | \
        sed "s/$1//; s/://" | \
        awk '{ print toupper($NF) }')
}

report_short_name "$(hyprctl devices -j | jq -r '.keyboards | map(select(.main))[0].active_keymap')"

prefix="activelayout>>at-translated-set-2-keyboard,"
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    case $line in
        $prefix*) report_short_name "${line#$prefix}";;
    esac
done
