#! /usr/bin/sh

get_workspaces() {
    WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
    seq 1 10 | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -c 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

get_workspaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    case $line in
        movewindow*|openwindow*|closewindow*) get_workspaces
    esac
done
