#! /usr/bin/sh

WAIT_PID=""

wait_and_see() {
    grandparent=$(ps -o ppid= $(ps -o ppid= $WAIT_PID) | tr -d ' ')
    if [ "$grandparent" = "$$" ]; then
        kill $WAIT_PID
    fi
    (sleep 5; echo "{\"value\": $(brightnessctl get), \"recent\": false}") &
    WAIT_PID=$!
}

echo "{\"value\": $(brightnessctl get), \"recent\": false}"
acpi_listen | while read -r line; do
    case $line in
        video/brightness*)
            (sleep 0.1; echo "{\"value\": $(brightnessctl get), \"recent\": true}") &
            wait_and_see
    esac
done
