#! /usr/bin/sh

get_workspaces() {
    hyprctl clients -j | \
        jq -rc 'group_by(.workspace.id) | map({workspace: .[0].workspace, windows: sort_by(.at) | map({address, class, title: .title | sub(" — Mozilla Firefox"; "")})})'
}

get_workspaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    case $line in
        movewindow*|openwindow*|closewindow*|windowtitle*) get_workspaces
    esac
done
