#! /usr/bin/sh

last=""

get_current() {
    playerctl --list-all --no-messages | head -n 1
}

watch="type='signal',destination='org.mpris.MediaPlayer2',member='PropertiesChanged'"
dbus-monitor --session --profile "$watch" | while read -r line; do
    new=$(get_current)
    if [ "$last" != "$new" ]; then
        echo $new
        last=$new
    fi
done
